name: CodeQL

on:
  push:
    branches: [ dev, main, github-actions ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
      security-events: write
      issues: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        if: ${{ matrix.language == 'java' }}
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        if: ${{ matrix.language == 'java' }}
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended,security-and-quality

      - name: Autobuild
        if: ${{ matrix.language == 'java' }}
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.pull_request 
              ? context.payload.pull_request.number 
              : (context.payload.issue ? context.payload.issue.number : null);
            
            if (issue) {
              github.rest.issues.createComment({
                issue_number: issue,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '⚠️ CodeQL security scan failed. Please check the workflow logs.'
              });
            } else {
              console.log('No issue or PR number found, skipping comment creation');
            }